scoop install googlechrome
scoop install firefox
scoop install everything
scoop install powertoys
scoop install windows-terminal
scoop install clink
scoop install clink-completions
scoop install vscode
scoop install sysinternals
